name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12" ]
        resolution: [ "highest", "lowest-direct" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: 1-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}

    - name: Install ${{ matrix.resolution }} dependencies
      run: |
        python -m pip install --upgrade uv wheel
        uv pip install --system --upgrade --resolution ${{ matrix.resolution }} .[test]

    - name: Test with pytest
      run: |
        pytest --xdoc --cov=primap2 --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
